# Generated by Django 4.2.3 on 2023-07-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0002_alter_author_born_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='born_date',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='born_location',
            new_name='birthplace',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='fullname',
            new_name='name',
        ),
    ]
